/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkspaceClientIdRouteImport } from './routes/workspace/$clientId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as AdminVaultRouteImport } from './routes/admin/vault'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLedgerRouteImport } from './routes/admin/ledger'
import { Route as AdminInfrastructureRouteImport } from './routes/admin/infrastructure'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminDomainsRouteImport } from './routes/admin/domains'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiWebhooksTallyRouteImport } from './routes/api/webhooks/tally'
import { Route as ApiOutboundSendRouteImport } from './routes/api/outbound/send'
import { Route as ApiInboundResendRouteImport } from './routes/api/inbound/resend'
import { Route as ApiCronSweeperRouteImport } from './routes/api/cron/sweeper'
import { Route as ApiAdminOnboardClientRouteImport } from './routes/api/admin/onboard-client'
import { Route as AdminClientsClientSlugRouteImport } from './routes/admin/clients.$clientSlug'
import { Route as AdminClientIdRouteImport } from './routes/admin/client.$id'
import { Route as AdminClientIdIndexRouteImport } from './routes/admin/client.$id.index'
import { Route as AdminClientIdWorkflowRouteImport } from './routes/admin/client.$id.workflow'
import { Route as AdminClientIdVaultRouteImport } from './routes/admin/client.$id.vault'
import { Route as AdminClientIdTemplatesRouteImport } from './routes/admin/client.$id.templates'
import { Route as AdminClientIdSettingsRouteImport } from './routes/admin/client.$id.settings'
import { Route as AdminClientIdSequenceRouteImport } from './routes/admin/client.$id.sequence'
import { Route as AdminClientIdOutboundRouteImport } from './routes/admin/client.$id.outbound'
import { Route as AdminClientIdOrchestrationRouteImport } from './routes/admin/client.$id.orchestration'
import { Route as AdminClientIdLeadsRouteImport } from './routes/admin/client.$id.leads'
import { Route as AdminClientIdInfrastructureRouteImport } from './routes/admin/client.$id.infrastructure'
import { Route as AdminClientIdDashboardRouteImport } from './routes/admin/client.$id.dashboard'
import { Route as AdminClientIdCredentialsRouteImport } from './routes/admin/client.$id.credentials'
import { Route as AdminClientIdAgentsAgentIdRouteImport } from './routes/admin/client.$id.agents.$agentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceClientIdRoute = WorkspaceClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultRoute = AdminVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiWebhooksTallyRoute = ApiWebhooksTallyRouteImport.update({
  id: '/api/webhooks/tally',
  path: '/api/webhooks/tally',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutboundSendRoute = ApiOutboundSendRouteImport.update({
  id: '/api/outbound/send',
  path: '/api/outbound/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboundResendRoute = ApiInboundResendRouteImport.update({
  id: '/api/inbound/resend',
  path: '/api/inbound/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSweeperRoute = ApiCronSweeperRouteImport.update({
  id: '/api/cron/sweeper',
  path: '/api/cron/sweeper',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOnboardClientRoute = ApiAdminOnboardClientRouteImport.update({
  id: '/api/admin/onboard-client',
  path: '/api/admin/onboard-client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsClientSlugRoute = AdminClientsClientSlugRouteImport.update({
  id: '/clients/$clientSlug',
  path: '/clients/$clientSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientIdRoute = AdminClientIdRouteImport.update({
  id: '/client/$id',
  path: '/client/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientIdIndexRoute = AdminClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdWorkflowRoute = AdminClientIdWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdVaultRoute = AdminClientIdVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdTemplatesRoute = AdminClientIdTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdSettingsRoute = AdminClientIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdSequenceRoute = AdminClientIdSequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdOutboundRoute = AdminClientIdOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdOrchestrationRoute =
  AdminClientIdOrchestrationRouteImport.update({
    id: '/orchestration',
    path: '/orchestration',
    getParentRoute: () => AdminClientIdRoute,
  } as any)
const AdminClientIdLeadsRoute = AdminClientIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdInfrastructureRoute =
  AdminClientIdInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AdminClientIdRoute,
  } as any)
const AdminClientIdDashboardRoute = AdminClientIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdCredentialsRoute =
  AdminClientIdCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AdminClientIdRoute,
  } as any)
const AdminClientIdAgentsAgentIdRoute =
  AdminClientIdAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AdminClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/health': typeof ApiHealthRoute
  '/workspace/$clientId': typeof WorkspaceClientIdRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/admin/client/$id': typeof AdminClientIdRouteWithChildren
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/api/admin/onboard-client': typeof ApiAdminOnboardClientRoute
  '/api/cron/sweeper': typeof ApiCronSweeperRoute
  '/api/inbound/resend': typeof ApiInboundResendRoute
  '/api/outbound/send': typeof ApiOutboundSendRoute
  '/api/webhooks/tally': typeof ApiWebhooksTallyRoute
  '/admin/client/$id/credentials': typeof AdminClientIdCredentialsRoute
  '/admin/client/$id/dashboard': typeof AdminClientIdDashboardRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/sequence': typeof AdminClientIdSequenceRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/templates': typeof AdminClientIdTemplatesRoute
  '/admin/client/$id/vault': typeof AdminClientIdVaultRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id/': typeof AdminClientIdIndexRoute
  '/admin/client/$id/agents/$agentId': typeof AdminClientIdAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/health': typeof ApiHealthRoute
  '/workspace/$clientId': typeof WorkspaceClientIdRoute
  '/admin': typeof AdminIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/api/admin/onboard-client': typeof ApiAdminOnboardClientRoute
  '/api/cron/sweeper': typeof ApiCronSweeperRoute
  '/api/inbound/resend': typeof ApiInboundResendRoute
  '/api/outbound/send': typeof ApiOutboundSendRoute
  '/api/webhooks/tally': typeof ApiWebhooksTallyRoute
  '/admin/client/$id/credentials': typeof AdminClientIdCredentialsRoute
  '/admin/client/$id/dashboard': typeof AdminClientIdDashboardRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/sequence': typeof AdminClientIdSequenceRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/templates': typeof AdminClientIdTemplatesRoute
  '/admin/client/$id/vault': typeof AdminClientIdVaultRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id': typeof AdminClientIdIndexRoute
  '/admin/client/$id/agents/$agentId': typeof AdminClientIdAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/health': typeof ApiHealthRoute
  '/workspace/$clientId': typeof WorkspaceClientIdRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/admin/client/$id': typeof AdminClientIdRouteWithChildren
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/api/admin/onboard-client': typeof ApiAdminOnboardClientRoute
  '/api/cron/sweeper': typeof ApiCronSweeperRoute
  '/api/inbound/resend': typeof ApiInboundResendRoute
  '/api/outbound/send': typeof ApiOutboundSendRoute
  '/api/webhooks/tally': typeof ApiWebhooksTallyRoute
  '/admin/client/$id/credentials': typeof AdminClientIdCredentialsRoute
  '/admin/client/$id/dashboard': typeof AdminClientIdDashboardRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/sequence': typeof AdminClientIdSequenceRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/templates': typeof AdminClientIdTemplatesRoute
  '/admin/client/$id/vault': typeof AdminClientIdVaultRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id/': typeof AdminClientIdIndexRoute
  '/admin/client/$id/agents/$agentId': typeof AdminClientIdAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/workspace'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/credentials'
    | '/admin/domains'
    | '/admin/inbox'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/vault'
    | '/api/agent'
    | '/api/health'
    | '/workspace/$clientId'
    | '/admin/'
    | '/workspace/'
    | '/admin/client/$id'
    | '/admin/clients/$clientSlug'
    | '/api/admin/onboard-client'
    | '/api/cron/sweeper'
    | '/api/inbound/resend'
    | '/api/outbound/send'
    | '/api/webhooks/tally'
    | '/admin/client/$id/credentials'
    | '/admin/client/$id/dashboard'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/sequence'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/templates'
    | '/admin/client/$id/vault'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id/'
    | '/admin/client/$id/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/credentials'
    | '/admin/domains'
    | '/admin/inbox'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/vault'
    | '/api/agent'
    | '/api/health'
    | '/workspace/$clientId'
    | '/admin'
    | '/workspace'
    | '/admin/clients/$clientSlug'
    | '/api/admin/onboard-client'
    | '/api/cron/sweeper'
    | '/api/inbound/resend'
    | '/api/outbound/send'
    | '/api/webhooks/tally'
    | '/admin/client/$id/credentials'
    | '/admin/client/$id/dashboard'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/sequence'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/templates'
    | '/admin/client/$id/vault'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id'
    | '/admin/client/$id/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/workspace'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/credentials'
    | '/admin/domains'
    | '/admin/inbox'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/vault'
    | '/api/agent'
    | '/api/health'
    | '/workspace/$clientId'
    | '/admin/'
    | '/workspace/'
    | '/admin/client/$id'
    | '/admin/clients/$clientSlug'
    | '/api/admin/onboard-client'
    | '/api/cron/sweeper'
    | '/api/inbound/resend'
    | '/api/outbound/send'
    | '/api/webhooks/tally'
    | '/admin/client/$id/credentials'
    | '/admin/client/$id/dashboard'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/sequence'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/templates'
    | '/admin/client/$id/vault'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id/'
    | '/admin/client/$id/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAdminOnboardClientRoute: typeof ApiAdminOnboardClientRoute
  ApiCronSweeperRoute: typeof ApiCronSweeperRoute
  ApiInboundResendRoute: typeof ApiInboundResendRoute
  ApiOutboundSendRoute: typeof ApiOutboundSendRoute
  ApiWebhooksTallyRoute: typeof ApiWebhooksTallyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$clientId': {
      id: '/workspace/$clientId'
      path: '/$clientId'
      fullPath: '/workspace/$clientId'
      preLoaderRoute: typeof WorkspaceClientIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault': {
      id: '/admin/vault'
      path: '/vault'
      fullPath: '/admin/vault'
      preLoaderRoute: typeof AdminVaultRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/webhooks/tally': {
      id: '/api/webhooks/tally'
      path: '/api/webhooks/tally'
      fullPath: '/api/webhooks/tally'
      preLoaderRoute: typeof ApiWebhooksTallyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outbound/send': {
      id: '/api/outbound/send'
      path: '/api/outbound/send'
      fullPath: '/api/outbound/send'
      preLoaderRoute: typeof ApiOutboundSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbound/resend': {
      id: '/api/inbound/resend'
      path: '/api/inbound/resend'
      fullPath: '/api/inbound/resend'
      preLoaderRoute: typeof ApiInboundResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sweeper': {
      id: '/api/cron/sweeper'
      path: '/api/cron/sweeper'
      fullPath: '/api/cron/sweeper'
      preLoaderRoute: typeof ApiCronSweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/onboard-client': {
      id: '/api/admin/onboard-client'
      path: '/api/admin/onboard-client'
      fullPath: '/api/admin/onboard-client'
      preLoaderRoute: typeof ApiAdminOnboardClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/$clientSlug': {
      id: '/admin/clients/$clientSlug'
      path: '/clients/$clientSlug'
      fullPath: '/admin/clients/$clientSlug'
      preLoaderRoute: typeof AdminClientsClientSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$id': {
      id: '/admin/client/$id'
      path: '/client/$id'
      fullPath: '/admin/client/$id'
      preLoaderRoute: typeof AdminClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$id/': {
      id: '/admin/client/$id/'
      path: '/'
      fullPath: '/admin/client/$id/'
      preLoaderRoute: typeof AdminClientIdIndexRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/workflow': {
      id: '/admin/client/$id/workflow'
      path: '/workflow'
      fullPath: '/admin/client/$id/workflow'
      preLoaderRoute: typeof AdminClientIdWorkflowRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/vault': {
      id: '/admin/client/$id/vault'
      path: '/vault'
      fullPath: '/admin/client/$id/vault'
      preLoaderRoute: typeof AdminClientIdVaultRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/templates': {
      id: '/admin/client/$id/templates'
      path: '/templates'
      fullPath: '/admin/client/$id/templates'
      preLoaderRoute: typeof AdminClientIdTemplatesRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/settings': {
      id: '/admin/client/$id/settings'
      path: '/settings'
      fullPath: '/admin/client/$id/settings'
      preLoaderRoute: typeof AdminClientIdSettingsRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/sequence': {
      id: '/admin/client/$id/sequence'
      path: '/sequence'
      fullPath: '/admin/client/$id/sequence'
      preLoaderRoute: typeof AdminClientIdSequenceRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/outbound': {
      id: '/admin/client/$id/outbound'
      path: '/outbound'
      fullPath: '/admin/client/$id/outbound'
      preLoaderRoute: typeof AdminClientIdOutboundRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/orchestration': {
      id: '/admin/client/$id/orchestration'
      path: '/orchestration'
      fullPath: '/admin/client/$id/orchestration'
      preLoaderRoute: typeof AdminClientIdOrchestrationRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/leads': {
      id: '/admin/client/$id/leads'
      path: '/leads'
      fullPath: '/admin/client/$id/leads'
      preLoaderRoute: typeof AdminClientIdLeadsRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/infrastructure': {
      id: '/admin/client/$id/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/client/$id/infrastructure'
      preLoaderRoute: typeof AdminClientIdInfrastructureRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/dashboard': {
      id: '/admin/client/$id/dashboard'
      path: '/dashboard'
      fullPath: '/admin/client/$id/dashboard'
      preLoaderRoute: typeof AdminClientIdDashboardRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/credentials': {
      id: '/admin/client/$id/credentials'
      path: '/credentials'
      fullPath: '/admin/client/$id/credentials'
      preLoaderRoute: typeof AdminClientIdCredentialsRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/agents/$agentId': {
      id: '/admin/client/$id/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/admin/client/$id/agents/$agentId'
      preLoaderRoute: typeof AdminClientIdAgentsAgentIdRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
  }
}

interface AdminClientIdRouteChildren {
  AdminClientIdCredentialsRoute: typeof AdminClientIdCredentialsRoute
  AdminClientIdDashboardRoute: typeof AdminClientIdDashboardRoute
  AdminClientIdInfrastructureRoute: typeof AdminClientIdInfrastructureRoute
  AdminClientIdLeadsRoute: typeof AdminClientIdLeadsRoute
  AdminClientIdOrchestrationRoute: typeof AdminClientIdOrchestrationRoute
  AdminClientIdOutboundRoute: typeof AdminClientIdOutboundRoute
  AdminClientIdSequenceRoute: typeof AdminClientIdSequenceRoute
  AdminClientIdSettingsRoute: typeof AdminClientIdSettingsRoute
  AdminClientIdTemplatesRoute: typeof AdminClientIdTemplatesRoute
  AdminClientIdVaultRoute: typeof AdminClientIdVaultRoute
  AdminClientIdWorkflowRoute: typeof AdminClientIdWorkflowRoute
  AdminClientIdIndexRoute: typeof AdminClientIdIndexRoute
  AdminClientIdAgentsAgentIdRoute: typeof AdminClientIdAgentsAgentIdRoute
}

const AdminClientIdRouteChildren: AdminClientIdRouteChildren = {
  AdminClientIdCredentialsRoute: AdminClientIdCredentialsRoute,
  AdminClientIdDashboardRoute: AdminClientIdDashboardRoute,
  AdminClientIdInfrastructureRoute: AdminClientIdInfrastructureRoute,
  AdminClientIdLeadsRoute: AdminClientIdLeadsRoute,
  AdminClientIdOrchestrationRoute: AdminClientIdOrchestrationRoute,
  AdminClientIdOutboundRoute: AdminClientIdOutboundRoute,
  AdminClientIdSequenceRoute: AdminClientIdSequenceRoute,
  AdminClientIdSettingsRoute: AdminClientIdSettingsRoute,
  AdminClientIdTemplatesRoute: AdminClientIdTemplatesRoute,
  AdminClientIdVaultRoute: AdminClientIdVaultRoute,
  AdminClientIdWorkflowRoute: AdminClientIdWorkflowRoute,
  AdminClientIdIndexRoute: AdminClientIdIndexRoute,
  AdminClientIdAgentsAgentIdRoute: AdminClientIdAgentsAgentIdRoute,
}

const AdminClientIdRouteWithChildren = AdminClientIdRoute._addFileChildren(
  AdminClientIdRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminVaultRoute: typeof AdminVaultRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientIdRoute: typeof AdminClientIdRouteWithChildren
  AdminClientsClientSlugRoute: typeof AdminClientsClientSlugRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminVaultRoute: AdminVaultRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientIdRoute: AdminClientIdRouteWithChildren,
  AdminClientsClientSlugRoute: AdminClientsClientSlugRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface WorkspaceRouteRouteChildren {
  WorkspaceClientIdRoute: typeof WorkspaceClientIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceClientIdRoute: WorkspaceClientIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAdminOnboardClientRoute: ApiAdminOnboardClientRoute,
  ApiCronSweeperRoute: ApiCronSweeperRoute,
  ApiInboundResendRoute: ApiInboundResendRoute,
  ApiOutboundSendRoute: ApiOutboundSendRoute,
  ApiWebhooksTallyRoute: ApiWebhooksTallyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
