/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as AdminVaultRouteImport } from './routes/admin/vault'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLedgerRouteImport } from './routes/admin/ledger'
import { Route as AdminInfrastructureRouteImport } from './routes/admin/infrastructure'
import { Route as AdminClientsClientSlugRouteImport } from './routes/admin/clients.$clientSlug'
import { Route as AdminClientIdRouteImport } from './routes/admin/client.$id'
import { Route as AdminClientIdIndexRouteImport } from './routes/admin/client.$id.index'
import { Route as AdminClientIdWorkflowRouteImport } from './routes/admin/client.$id.workflow'
import { Route as AdminClientIdSettingsRouteImport } from './routes/admin/client.$id.settings'
import { Route as AdminClientIdOutboundRouteImport } from './routes/admin/client.$id.outbound'
import { Route as AdminClientIdOrchestrationRouteImport } from './routes/admin/client.$id.orchestration'
import { Route as AdminClientIdLeadsRouteImport } from './routes/admin/client.$id.leads'
import { Route as AdminClientIdInfrastructureRouteImport } from './routes/admin/client.$id.infrastructure'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultRoute = AdminVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsClientSlugRoute = AdminClientsClientSlugRouteImport.update({
  id: '/clients/$clientSlug',
  path: '/clients/$clientSlug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientIdRoute = AdminClientIdRouteImport.update({
  id: '/client/$id',
  path: '/client/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientIdIndexRoute = AdminClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdWorkflowRoute = AdminClientIdWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdSettingsRoute = AdminClientIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdOutboundRoute = AdminClientIdOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdOrchestrationRoute =
  AdminClientIdOrchestrationRouteImport.update({
    id: '/orchestration',
    path: '/orchestration',
    getParentRoute: () => AdminClientIdRoute,
  } as any)
const AdminClientIdLeadsRoute = AdminClientIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminClientIdRoute,
} as any)
const AdminClientIdInfrastructureRoute =
  AdminClientIdInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AdminClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/client/$id': typeof AdminClientIdRouteWithChildren
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id/': typeof AdminClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id': typeof AdminClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/agent': typeof ApiAgentRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/client/$id': typeof AdminClientIdRouteWithChildren
  '/admin/clients/$clientSlug': typeof AdminClientsClientSlugRoute
  '/admin/client/$id/infrastructure': typeof AdminClientIdInfrastructureRoute
  '/admin/client/$id/leads': typeof AdminClientIdLeadsRoute
  '/admin/client/$id/orchestration': typeof AdminClientIdOrchestrationRoute
  '/admin/client/$id/outbound': typeof AdminClientIdOutboundRoute
  '/admin/client/$id/settings': typeof AdminClientIdSettingsRoute
  '/admin/client/$id/workflow': typeof AdminClientIdWorkflowRoute
  '/admin/client/$id/': typeof AdminClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/workspace'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/vault'
    | '/api/agent'
    | '/admin/'
    | '/admin/client/$id'
    | '/admin/clients/$clientSlug'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/vault'
    | '/api/agent'
    | '/admin'
    | '/admin/clients/$clientSlug'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/workspace'
    | '/admin/infrastructure'
    | '/admin/ledger'
    | '/admin/logs'
    | '/admin/vault'
    | '/api/agent'
    | '/admin/'
    | '/admin/client/$id'
    | '/admin/clients/$clientSlug'
    | '/admin/client/$id/infrastructure'
    | '/admin/client/$id/leads'
    | '/admin/client/$id/orchestration'
    | '/admin/client/$id/outbound'
    | '/admin/client/$id/settings'
    | '/admin/client/$id/workflow'
    | '/admin/client/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAgentRoute: typeof ApiAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault': {
      id: '/admin/vault'
      path: '/vault'
      fullPath: '/admin/vault'
      preLoaderRoute: typeof AdminVaultRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients/$clientSlug': {
      id: '/admin/clients/$clientSlug'
      path: '/clients/$clientSlug'
      fullPath: '/admin/clients/$clientSlug'
      preLoaderRoute: typeof AdminClientsClientSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$id': {
      id: '/admin/client/$id'
      path: '/client/$id'
      fullPath: '/admin/client/$id'
      preLoaderRoute: typeof AdminClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$id/': {
      id: '/admin/client/$id/'
      path: '/'
      fullPath: '/admin/client/$id/'
      preLoaderRoute: typeof AdminClientIdIndexRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/workflow': {
      id: '/admin/client/$id/workflow'
      path: '/workflow'
      fullPath: '/admin/client/$id/workflow'
      preLoaderRoute: typeof AdminClientIdWorkflowRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/settings': {
      id: '/admin/client/$id/settings'
      path: '/settings'
      fullPath: '/admin/client/$id/settings'
      preLoaderRoute: typeof AdminClientIdSettingsRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/outbound': {
      id: '/admin/client/$id/outbound'
      path: '/outbound'
      fullPath: '/admin/client/$id/outbound'
      preLoaderRoute: typeof AdminClientIdOutboundRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/orchestration': {
      id: '/admin/client/$id/orchestration'
      path: '/orchestration'
      fullPath: '/admin/client/$id/orchestration'
      preLoaderRoute: typeof AdminClientIdOrchestrationRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/leads': {
      id: '/admin/client/$id/leads'
      path: '/leads'
      fullPath: '/admin/client/$id/leads'
      preLoaderRoute: typeof AdminClientIdLeadsRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
    '/admin/client/$id/infrastructure': {
      id: '/admin/client/$id/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/client/$id/infrastructure'
      preLoaderRoute: typeof AdminClientIdInfrastructureRouteImport
      parentRoute: typeof AdminClientIdRoute
    }
  }
}

interface AdminClientIdRouteChildren {
  AdminClientIdInfrastructureRoute: typeof AdminClientIdInfrastructureRoute
  AdminClientIdLeadsRoute: typeof AdminClientIdLeadsRoute
  AdminClientIdOrchestrationRoute: typeof AdminClientIdOrchestrationRoute
  AdminClientIdOutboundRoute: typeof AdminClientIdOutboundRoute
  AdminClientIdSettingsRoute: typeof AdminClientIdSettingsRoute
  AdminClientIdWorkflowRoute: typeof AdminClientIdWorkflowRoute
  AdminClientIdIndexRoute: typeof AdminClientIdIndexRoute
}

const AdminClientIdRouteChildren: AdminClientIdRouteChildren = {
  AdminClientIdInfrastructureRoute: AdminClientIdInfrastructureRoute,
  AdminClientIdLeadsRoute: AdminClientIdLeadsRoute,
  AdminClientIdOrchestrationRoute: AdminClientIdOrchestrationRoute,
  AdminClientIdOutboundRoute: AdminClientIdOutboundRoute,
  AdminClientIdSettingsRoute: AdminClientIdSettingsRoute,
  AdminClientIdWorkflowRoute: AdminClientIdWorkflowRoute,
  AdminClientIdIndexRoute: AdminClientIdIndexRoute,
}

const AdminClientIdRouteWithChildren = AdminClientIdRoute._addFileChildren(
  AdminClientIdRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminVaultRoute: typeof AdminVaultRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientIdRoute: typeof AdminClientIdRouteWithChildren
  AdminClientsClientSlugRoute: typeof AdminClientsClientSlugRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminVaultRoute: AdminVaultRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientIdRoute: AdminClientIdRouteWithChildren,
  AdminClientsClientSlugRoute: AdminClientsClientSlugRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
  ApiAgentRoute: ApiAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
